name: Update Poduction Website

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload www directory via ftp
        env:
            FTP_USER: ${{ secrets.FTP_USER }}
            FTP_PASS: ${{ secrets.FTP_PASS }}
        run: find www -type f -exec curl -u $FTP_USER:$FTP_PASS --ftp-create-dirs -T {} ftp://ftp.online.net/recherche-dpo.opendata/{} \;
