name: Update DPO database

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build-db-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create databases
        run: |
          cd data
          ./prepare-data.sh

      - name: Upload database to production website
        run: curl -u $FTP_USER:$FTP_PASS -T www/private/data/data.db ftp://ftp.online.net/recherche-dpo.opendata/private/data/data.db
